version: '3.3'

services:
  db:
    image: kartoza/postgis
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: "exit 0"
    ports:
      - '5435:5432'

  dbbackups:
    image: kartoza/pg-backup:13.0
    volumes:
      - db-backups:/backups
    environment:
      - DUMPPREFIX=PG_gis
      - POSTGRES_HOST=db
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_PORT=5432
      - STORAGE_BACKEND="FILE"
      - DUMP_ARGS="-Fc"
      #- DB_TABLES=yes
      # Add a custom archive so that it can be used to restore as a test
      #- ARCHIVE_FILENAME=latest
      # For restore script
      #- TARGET_DB=gis_restore
      #- WITH_POSTGIS=1
      #- TARGET_ARCHIVE=/backups/latest.gis.dmp
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-backups:
  db-data: